# Generated by Django 5.1 on 2025-02-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('producer', 'Producer'), ('consumer', 'Consumer')], default='producer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('collected', 'Collected'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('buckets', models.IntegerField()),
                ('bags', models.IntegerField()),
                ('mill', models.CharField(choices=[('mill_1', 'Mill_1'), ('mill_2', 'Mill_2'), ('mill_3', 'Mill_3')], default='mill_1', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.user')),
            ],
        ),
    ]
