# Generated by Django 5.1 on 2024-10-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_user_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
