# Generated by Django 5.1 on 2025-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('producer', 'Producer'), ('factory', 'Factory'), ('transporter', 'Transporter')], default='producer', max_length=12),
        ),
    ]
