# Generated by Django 5.1 on 2024-10-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
