# Generated by Django 5.1 on 2024-10-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='buckets',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
